# Generated by Django 2.1.2 on 2018-11-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('website_name', models.CharField(max_length=264, unique=True)),
                ('website_url', models.URLField(unique=True)),
                ('access_date', models.DateField()),
            ],
        ),
    ]
